server:
  port: 8081
  
spring:     
  devtools:
    restart:
      enabled: true    
  datasource:
    url: jdbc:mysql://localhost:3306/inventory?autoReconnect=true&useSSL=false
    username: mysqluser
    password: mysqlpw
      
  kafka:
    consumer:
      bootstrap-servers:
        - localhost:9092
      group-id: withdrwal-event
      auto-offset-reset: earliest
      
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:      
       ack-mode: MANUAL_IMMEDIATE
    producer:
      bootstrap-servers: localhost:9092    
